<#
.SYNOPSIS
    Writes frontend/.env.local from deployments/latest.json.

.DESCRIPTION
    Final step of the reproducible deployment pipeline:
        deploy + initialize -> record contract IDs -> configure frontend env

    Keeps the frontend from ever needing a manually copy-pasted contract ID.
    Re-run this any time you redeploy or point at a different deployment
    record.

.EXAMPLE
    ./scripts/configure-frontend.ps1
    ./scripts/configure-frontend.ps1 -DeploymentFile deployments/testnet-20260101-120000.json
#>

param(
    [string]$DeploymentFile = "deployments/latest.json",
    [string]$Network = "testnet"
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$deploymentPath = Join-Path $repoRoot $DeploymentFile

if (-not (Test-Path $deploymentPath)) {
    throw "Deployment record not found at $deploymentPath. Run ./scripts/deploy.ps1 first."
}

$record = Get-Content $deploymentPath -Raw | ConvertFrom-Json

$rpcUrls = @{
    testnet = "https://soroban-testnet.stellar.org"
    futurenet = "https://rpc-futurenet.stellar.org"
    mainnet = "https://mainnet.sorobanrpc.com"
}
$passphrases = @{
    testnet = "Test SDF Network ; September 2015"
    futurenet = "Test SDF Future Network ; October 2022"
    mainnet = "Public Global Stellar Network ; September 2015"
}

$envContent = @"
# Auto-generated by scripts/configure-frontend.ps1 on $(Get-Date -Format o)
# Do NOT commit this file. See .env.example for the documented template.

NEXT_PUBLIC_STELLAR_NETWORK=$Network
NEXT_PUBLIC_SOROBAN_RPC_URL=$($rpcUrls[$Network])
NEXT_PUBLIC_NETWORK_PASSPHRASE=$($passphrases[$Network])
NEXT_PUBLIC_FACTORY_CONTRACT_ID=$($record.factoryContractId)
NEXT_PUBLIC_TOKEN_CONTRACT_ID=$($record.tokenAddress)
NEXT_PUBLIC_DEFAULT_CLAIM_TIMEOUT_SECS=$($record.defaultClaimTimeoutSecs)
"@

$frontendEnvPath = Join-Path $repoRoot "frontend/.env.local"
Set-Content -Path $frontendEnvPath -Value $envContent -Encoding UTF8

Write-Host "==> Wrote $frontendEnvPath" -ForegroundColor Green
Write-Host "    factory: $($record.factoryContractId)"
Write-Host "    token:   $($record.tokenAddress)"
Write-Host "    network: $Network"
